# Generated by Django 4.1.1 on 2022-10-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestquiz',
            name='kvitancia',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='Квитанция'),
        ),
    ]
