# Generated by Django 4.1.1 on 2022-11-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial_request', '0002_requestquiz_kvitancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestquiz',
            name='kvitancia',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='Квитанция договор'),
        ),
        migrations.AlterField(
            model_name='requestquiz',
            name='name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Ответственное лицо(ФИО)'),
        ),
    ]
