# Generated by Django 4.1.1 on 2022-11-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial_request', '0003_alter_requestquiz_kvitancia_alter_requestquiz_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudent',
            name='excel_file',
            field=models.FileField(default=1, upload_to='files', verbose_name='Excel ученики'),
            preserve_default=False,
        ),
    ]
