# Generated by Django 4.1.1 on 2022-12-28 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=255, verbose_name='Регион')),
            ],
            options={
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lng_title', models.CharField(blank=True, max_length=200, null=True)),
                ('subject_title', models.CharField(blank=True, max_length=200, verbose_name='Предмет')),
                ('number_of_questions', models.IntegerField(blank=True, default=15, null=True, verbose_name='Количество вопросов')),
                ('simestr', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1, null=True, verbose_name='Четверть')),
                ('time', models.IntegerField(blank=True, help_text='В минутах', null=True, verbose_name='Время теста')),
                ('required_score_to_pass', models.IntegerField(blank=True, help_text='%', null=True, verbose_name='Проходной балл ')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizes.grade')),
            ],
            options={
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, max_length=3000, null=True)),
                ('image_path', models.CharField(blank=True, max_length=2500, null=True)),
                ('var1', models.CharField(blank=True, max_length=3000, null=True)),
                ('var2', models.CharField(blank=True, max_length=3000, null=True)),
                ('var3', models.CharField(blank=True, max_length=3000, null=True)),
                ('var4', models.CharField(blank=True, max_length=3000, null=True)),
                ('var5', models.CharField(blank=True, max_length=3000, null=True)),
                ('answers', models.CharField(blank=True, max_length=20, null=True)),
                ('subject_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizes.quiz')),
            ],
            options={
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial_name', models.CharField(max_length=255, verbose_name='Филиал')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizes.region')),
            ],
            options={
                'verbose_name_plural': 'Филиал',
            },
        ),
    ]
