# Generated by Django 4.1.1 on 2022-10-21 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='name',
        ),
        migrations.AddField(
            model_name='quiz',
            name='grade2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizes.grade'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='lng_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='lng_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='simestr',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1, null=True, verbose_name='Четверть'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='subject_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='school',
            name='filial_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizes.filial'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='grade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='number_of_questions',
            field=models.IntegerField(blank=True, default=15, null=True, verbose_name='Количество вопросов'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='required_score_to_pass',
            field=models.IntegerField(blank=True, help_text='%', null=True, verbose_name='Проходной балл '),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(blank=True, help_text='В минутах', null=True, verbose_name='Время теста'),
        ),
        
    ]
