# Generated by Django 4.1.1 on 2022-12-28 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_remove_quiz_simestr_question_simestr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filial',
        ),
    ]
