# Generated by Django 4.1.1 on 2022-11-17 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_quizlanguage_remove_quiz_grade_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='language',
        ),
    ]
