# Generated by Django 4.1.1 on 2022-12-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_delete_filial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='grade',
        ),
        migrations.AddField(
            model_name='question',
            name='grade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
