# Generated by Django 4.1.1 on 2022-12-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0004_remove_quiz_grade_question_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='required_score_to_pass',
            field=models.IntegerField(blank=True, default=50, help_text='%', null=True, verbose_name='Проходной балл '),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(blank=True, default=45, help_text='В минутах', null=True, verbose_name='Время теста'),
        ),
    ]
