# Generated by Django 4.1.1 on 2022-11-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0004_remove_quiz_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='fifth_quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='first_quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='fourth_quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='second_quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='third_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
