# Generated by Django 4.1.1 on 2022-11-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0005_quiz_fifth_quiz_quiz_first_quiz_quiz_fourth_quiz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='fifth_quiz',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='first_quiz',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='fourth_quiz',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='second_quiz',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='third_quiz',
        ),
        migrations.AddField(
            model_name='question',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
