# Generated by Django 4.1.1 on 2022-11-28 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0006_remove_quiz_fifth_quiz_remove_quiz_first_quiz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'Вопросы'},
        ),
    ]
